kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: config-reader
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: [configmaps", "secrets"]
  verbs: ["get", "watch", "list"]