apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spring-kubernetes-config
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: config-reader
subjects:
- kind: ServiceAccount
  name: spring-kubernetes
  namespace: default